# frozen_string_literal: true

source "https://rubygems.org"

#git_source(:github) {|KatrinaMarquez_T1A2| "https://github.com/#{KatrinaMarquez_T1A2}" }

# gem "rails"

gem "colorize", "~> 0.8.1"
gem 'tty-prompt'
